# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master
  
pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Debug'
  azureSubscriptionEndpoint: grimmukogooglemail.onmicrosoft.com  
  WebAppName: BuildNRun

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish and zip'
  inputs:
    command: publish
    publishWebProjects: False
    projects: $(SolutionPath)
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: AzureWebApp@1
  displayName: 'Deploy Azure Web App'
  inputs:
    azureSubscription: $(azureSubscriptionEndpoint)
    appName: $(WebAppName)
    appType: 'webApp'
    package: $(Build.ArtifactStagingDirectory)/**/*.zip    